### ISSUE TITLE
Embed media in mails, instead of refering to them through web URL

### ISSUE THREAD

**Issue by Riduidel** [rcarmo/rss2imap#18]
I plan to use rss2imap to get my feeds on my smartphone, then read them while not connected. To have a nice reading experience, having the images embedded in mail messages would be a must-have. Is it feasable to have images embedded in such a way (I'm not particularly aware of MUA web rendering peculiarities) ?

**Comment by rcarmo** [comment]
In my experience, no mobile MUA does this "right". Most of them will fetch messages from SRC tags, but inlining them never worked right.

Doubly so if you're on Android. Seriously.
